name: Release App

on:
  push:
    branches:
     - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Restore playstore.keystore.jks
        run: echo $KEYSTORE_ddvFILE | base64 -d > /tmp/playstore.keystore.jks
      - name: Restore key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=/tmp/playstore.keystore.jks" >> android/key.properties
        shell: bash
      - name: Build Android Appbundle
        run: flutter build appbundle
    
    
