name: Release App

on:
  push:
    tags:
      - 'v*'
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Restore playstore.keystore.jks
        id: write_jks_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'playstore.keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}
      - name: Restore key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=${{ steps.write_jks_file.outputs.filePath }}" >> android/key.properties
        shell: bash
      - name: Build Android APKs
        run: flutter build apk --split-per-abi
    
    
