name: Release App

on:
  push:
    branches:
     - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Build Android Appbundle
        run: flutter build appbundle
    
    
